services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
